/*         Character Makefile        */
/* Generated by Rane's V2 CHR editor */

pcx_name=FISHER4;
chr_name=FISHER4;
frame_w=32;
frame_h=32;
hot_x=8;
hot_y=8;
hot_w=16;
hot_h=16;
per_row=9;
total_frames=35;
lidle=0;
ridle=0;
uidle=0;
didle=0;
lscript=F0W10F1W10F2W10F3W10;
rscript=;
uscript=;
dscript=;

/* End of generated file. */
